### ISSUE TITLE
Do you have some kind of instructions?

### ISSUE THREAD

**Issue by swcrazyfan** [YukiKume/EqManage#5]
This web app you've built seems amazing! Do you have any kind of installation/setup instructions?

Based on my quick review of the code, it seems I need to write MySQL server details in the "serverconnect.php" file. Is there anything else? Will running the app automatically setup the tables?

Thanks!

**Comment by YukiKume** [comment]
Thanks for the interest in the project, unfortunately, this was my personal project back in high-school and it has some very rough edges (because I did not intend to open-source this and be used by others). If you are still willing to modify the files to make it usable, `serverconnect.php` is the right file to edit, alongside with `login.php` where you have to define the email server for to send registration email. 

There may be other files that contains `localhost`, I am not aware which particular ones that may contain it. 

It will not create a SQL table on startup, so I've attached an sqldump that should create the necessary files. Host an Apache server on the root directory, and go to login.php. You would have to first create an admin user so register a user with username `admin` on the very initial setup.

It will definitely have security issues so please use it on your own discretion

Apologies for the mess.

[Database file](https://github.com/YukiKume/EqManage/files/9332489/Database.zip)

_I should probably archive this repository..._
